# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fsr7-s4mT7YldN-QaEZxANCtz_wlMvt_
"""

import neuralstyletransfer

!pip install libsvm
!pip install pybrisque

from libsvm import svmutil
from brisque.brisque import *

brisq = BRISQUE()

brisq.get_feature("download.png")

brisq.get_score("download.png")